databases:
  - name: sites-saver
    databaseName: sites-saver
    user: postgres
    region: singapore
    plan: free

services:
  - type: web
    name: sitesSaver
    env: python
    region: singapore
    plan: free
    branch: main
    healthCheckPath: /
    buildCommand: "./build.sh"
    startCommand: "gunicorn sitesSaver.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: sites-saver
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true
